CREATE TABLE `fwversions`
(
    `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
	`version` VARCHAR(32) NOT NULL,
	`fwID` INT UNSIGNED REFERENCES `fws` (id) ON DELETE NO ACTION,
  	`hause` VARCHAR(32) NOT NULL,
  	`brand` VARCHAR(32) NOT NULL,
  	`model` VARCHAR(32) NOT NULL,
  	`oem` VARCHAR(32) NOT NULL,
  	`platform` VARCHAR(32) NOT NULL,
  	`language` VARCHAR(32) NOT NULL,
  	`fullimage` INT(1) UNSIGNED DEFAULT 0,
	`updatingdate` DATETIME,
	`creationdate` DATETIME
);
